title: Fernando Lezama's Homepage
url: "https://fernandolezama.github.io"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/fernandolezama"
footer_text: "Page design by Fernando Lezama"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/researcher/"
 - name: "About"
   link: "resume.pdf"
 - name: "Publication"
   link: "publication"
